[package]
name = "rust_proj"
version = "0.1.0"
authors = ["Adam Scislowicz <adam.scislowicz@gmail.com>"]
edition = "2021"

[dependencies]
pyo3 = { version = "0.14.5", features = ["extension-module"] }

[lib]
name = "submodule"
path = "lib.rs"
crate-type = ["cdylib"]